easy_admin:
    site_name: 'Arcadia Zoo Admin'
    design:
        brand_color: '#1ABC9C'
        assets:
            css: ['/css/admin.css']
    entities:
        Review:
            class: App\Entity\Review
            controller: App\Controller\Admin\ReviewCrudController
    enable_pretty_urls: false