framework:
    secret: '%env(APP_SECRET)%'
    session: true
    http_client:
        default_options:
            cafile: "C:/php/cacert.pem"
    profiler:
        enabled: false
        collect: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file