framework:
    secret: '%env(APP_SECRET)%'
    session: true
    http_client:
        default_options:
            cafile: "C:/php/cacert.pem"
    profiler:
        enabled: false
        collect: false
