when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false
    framework:
        profiler:
            enabled: false
            collect: false
when@test:
    framework:
        profiler: { collect: false }