<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250513084717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE animal_consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, animal_name VARCHAR(50) NOT NULL, consultation_count INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE contact_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT NOT NULL, email VARCHAR(180) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_consumption (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, heure TIME(0) WITHOUT TIME ZONE NOT NULL, nourriture VARCHAR(100) NOT NULL, quantite INT NOT NULL, animal_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8D49FB378E962C16 ON food_consumption (animal_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8D49FB37A76ED395 ON food_consumption (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(50) NOT NULL, commentaire TEXT NOT NULL, valide BOOLEAN NOT NULL, date_creation VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_794381C6A76ED395 ON review (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE veterinary_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, etat VARCHAR(50) NOT NULL, nourriture VARCHAR(100) NOT NULL, quantite INT NOT NULL, date_passage VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, animal_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_53C7E56B8E962C16 ON veterinary_report (animal_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_53C7E56BA76ED395 ON veterinary_report (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_consumption ADD CONSTRAINT FK_8D49FB378E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_consumption ADD CONSTRAINT FK_8D49FB37A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review ADD CONSTRAINT FK_794381C6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE veterinary_report ADD CONSTRAINT FK_53C7E56B8E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE veterinary_report ADD CONSTRAINT FK_53C7E56BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE food_consumption DROP CONSTRAINT FK_8D49FB378E962C16
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_consumption DROP CONSTRAINT FK_8D49FB37A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review DROP CONSTRAINT FK_794381C6A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE veterinary_report DROP CONSTRAINT FK_53C7E56B8E962C16
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE veterinary_report DROP CONSTRAINT FK_53C7E56BA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE animal_consultation
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE contact_request
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_consumption
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE review
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE service
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "user"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE veterinary_report
        SQL);
    }
}
