parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\TestLoggerController:
        arguments:
            $logger: '@monolog.logger.security'

    App\Security\AppAuthenticator:
        arguments:
            $logger: '@monolog.logger.security'